### ISSUE TITLE
R56: IndexError: list index out of range

### ISSUE THREAD

**Issue by NSQY** [SaltyChiang/VapourSynth-Plugins-Stub-Generator#3]
Hi, I believe the new API V4 has broken this tool. No problems with R54.

```
Python 3.9.7 [GCC 11.1.0] on linux
```

```
python -m pip install ./vsstubs
python -m vsstubs install package

Defaulting to user installation because normal site-packages is not writeable
Processing ./vsstubs
Building wheels for collected packages: vsstubs
  Building wheel for vsstubs (setup.py) ... done
  Created wheel for vsstubs: filename=vsstubs-0.1.1-py3-none-any.whl size=7852 sha256=58d0cfb105332cb02db4fae1f5684ef3d8e379ad7947d6a1e287cf5a900c6395
  Stored in directory: /tmp/pip-ephem-wheel-cache-24hwzkuq/wheels/65/1a/ac/f2bd322c6d07f430aca2cbcbfa4d1f9396d637cc4a004ce89c
Successfully built vsstubs
Installing collected packages: vsstubs
Successfully installed vsstubs-0.1.1
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nsqy/.local/lib/python3.9/site-packages/vsstubs/__main__.py", line 4, in <module>
    main()
  File "/home/nsqy/.local/lib/python3.9/site-packages/vsstubs/main.py", line 27, in main
    install(stubsdir, "__init__.pyi")
  File "/home/nsqy/.local/lib/python3.9/site-packages/vsstubs/install.py", line 5, in install
    pyi_content = generate.stub()
  File "/home/nsqy/.local/lib/python3.9/site-packages/vsstubs/generate.py", line 31, in stub
    plugins_meta = convert.plugins_vs2py(plugins)
  File "/home/nsqy/.local/lib/python3.9/site-packages/vsstubs/convert.py", line 64, in plugins_vs2py
    plugin_meta = PluginMeta(plugin["namespace"], plugin["name"], functions_vs2py(plugin["functions"]))
  File "/home/nsqy/.local/lib/python3.9/site-packages/vsstubs/convert.py", line 56, in functions_vs2py
    functions_core[name], functions_video[name] = function_params_vs2py(params)
  File "/home/nsqy/.local/lib/python3.9/site-packages/vsstubs/convert.py", line 33, in function_params_vs2py
    ptype = name_type_opt[1]
IndexError: list index out of range
```

**Comment by SaltyChiang** [comment]
Thank you for the issue.
The new version (0.2.0) should fix the issue and be compatible with VapourSynth R56 or newer (including AudioNode support).

**Comment by NSQY** [comment]
Confirmed working, thanks for the quick fix.
